server:
  port: 8081

spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/ucell
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true